### ISSUE TITLE
Lead could not be posted because Must specify `api_key`

### ISSUE THREAD

**Issue by svenporto-close** [llancon-rev/close_import_project#1]
When I tried to run a script as per `README.md` instructions, I got the script output saying:

```
Job Done!! total leads imported: 43
```

but nothing was actually imported.

Upon further investigation, it looks like the import is failing with a bunch of

```
Lead could not be posted because Must specify `api_key`
```
error.

What I'm doing wrong here? I've created the `.vault` file as per the `README.md` file and put my Close API key in there.

**Comment by llancon** [comment]
Hey @svenkapudija-close I wrote the wrong file name in the instructions. The file should be called "vault.env". I've updated the README.md as well.

**Comment by llancon** [comment]
However, I'd like to fix this bug, the script is misleading at moment. It shouldn't create the report with unimported leads and display that the leads were imported when the API calls fail. I'll work on this today.
